-- The icons Visual Player uses, and where to find each one in the icon font.
--
-- Generated by tools/update-icon-font.py from Tabler Icons 3.48.0.
-- Don't edit this by hand: add names to NEEDED_ICONS in that script
-- and run it again.

return {
    font_family = "tabler-icons",
    font_version = "3.48.0",
    codepoints = {
        ["badge-cc"] = 0xF55A,
        ["bluetooth"] = 0xEA37,
        ["check"] = 0xEA5E,
        ["chevron-down"] = 0xEA5F,
        ["chevron-up"] = 0xEA62,
        ["device-desktop"] = 0xEA89,
        ["device-laptop"] = 0xEB64,
        ["device-tv"] = 0xEA8D,
        ["eye"] = 0xEA9A,
        ["eye-off"] = 0xECF0,
        ["folder-open"] = 0xFAF7,
        ["gauge"] = 0xEAB1,
        ["info-circle"] = 0xEAC5,
        ["list"] = 0xEB6B,
        ["minus"] = 0xEAF2,
        ["movie"] = 0xEAFA,
        ["player-pause"] = 0xED45,
        ["player-play"] = 0xED46,
        ["player-skip-back"] = 0xED48,
        ["player-skip-forward"] = 0xED49,
        ["repeat"] = 0xEB72,
        ["repeat-once"] = 0xEB71,
        ["rotate-clockwise"] = 0xEB15,
        ["settings"] = 0xEB20,
        ["square"] = 0xEB2C,
        ["usb"] = 0xF00C,
        ["volume"] = 0xEB51,
        ["volume-2"] = 0xEB4F,
        ["volume-3"] = 0xEB50,
        ["x"] = 0xEB55,
    },
}
